services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_DATABASE: meshdata
      MYSQL_USER: meshdata
      MYSQL_PASSWORD: passw0rd
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - backend
  meshinfo:
    #image: ghcr.io/dadecoza/meshinfo-lite:0.1.5-za
    image: netnutmike/meshinfo:latest
    pull_policy: never
    depends_on:
      - mariadb
    volumes:
      - ./config.ini:/app/config.ini
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 80:8001
    networks:
      - backend
    restart: always

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/log:/mosquitto/log:rw
    restart: always

networks:       
  backend:
    driver: bridge
